version: '3.1'
services:
  Jhipster_courses-app:
    image: openjdk:11.0.11
    container_name: 'Jhipster_courses-app'
    restart: always
    #ports:
    #  - "8062:8080"
    volumes:
      - './build/libs/courses-0.0.1-SNAPSHOT.jar:/courses-0.0.1-SNAPSHOT.jar'
    command: ['java', '-jar', '/courses-0.0.1-SNAPSHOT.jar']
networks:
  default:
    external:
      name: courses_default
